ショッピングカートの商品表示機能の追加
danielkaneko/Shopping-Cart pull request #5
Opened 2022-09-15 07:13 UTC by danielkaneko

@nabemasamasa 
@Takatatsu9 
@konta3291 

ショッピングカートに商品表示機能を追加いたしました。
レビューをお願いいたします。

2022-09-15 07:59 UTC, nabemasamasa requested changes, later dismissed
ぱぶりっくは。。。 ( 3b358da2c951a450bc58113681de74c69e10edf5 まで )

2022-09-15 07:59 UTC, nabemasamasa commented on ShoppingCart/GoodsListMaker.vb
> +﻿Public Class GoodsListMaker
ぱぶりっく。。。

2022-09-15 07:59 UTC, nabemasamasa commented on ShoppingCart/GoodsListMaker.vb
> +        Public goodsName As String
ぱぶりっくは……

2022-09-15 07:59 UTC, nabemasamasa commented on ShoppingCart/GoodsListMaker.vb
> +    Public Function RegisterGoodsList() As List(Of GoodsProperty)
`Register`って「登録する」、普段、DBへの登録でこの`Register`をよく見る。
「登記」だったり、「記録」だったり、何かに書き込むこと、を考えると、確かにとも思う。

となると、Register以外で命名を推奨したいけど、、、
このメソッドの中身で私が命名するなら、`MakeGoodsList`かな。`GoodsListMaker`だし、なら`Make`はピッタリだし。

2022-09-15 07:59 UTC, nabemasamasa commented on ShoppingCart/ListShower.vb
> +﻿Public Class ListShower
ぱぶりっく……

2022-09-15 07:59 UTC, nabemasamasa commented on ShoppingCart/ListShower.vb
> +        For Each list In goodsList
listの型宣言が欲しいです。あと、ListをForEachした1要素が変数名`list`は嘘をついている変数名だと思う。

2022-09-15 07:59 UTC, nabemasamasa commented on ShoppingCart/GoodsListMaker.vb
> +    Public Class GoodsProperty
[nits] 「商品リストを作る」クラスの持ち物が「商品」なのは少し違和感。
「商品」は独立した1クラスの方が、「商品リストを作る」クラスを経由しなくていいし、他のクラスが参照しやすそう。
あと、`GoodsProperty`よりも直球`Goods`で良さそう。で、商品`Goods`が名前`Name`や詳細`Description`を持っている方が、より「オブジェクト指向」っぽくなりそう。

2022-09-15 07:59 UTC, nabemasamasa commented on ShoppingCart/ListShower.vb
> +                          "価格：" & list.goodsPrice & "円" & vbCrLf & "在庫数：" & list.goodsInventory)
[nits] ひとつのConsole.WriteLineでまとめるより、「商品名」「商品説明」で一個一個ConsoleWriteLineを呼ぶ方が、変更に強そう(要素を削除してほしい、要素を追加してほしい、、、、)

2022-09-15 08:07 UTC, danielkaneko commented on ShoppingCart/GoodsListMaker.vb
> +﻿Public Class GoodsListMaker
レビューありがとうございます。
コメントを追加いたします。

2022-09-15 08:07 UTC, danielkaneko commented on ShoppingCart/GoodsListMaker.vb
> +        Public goodsName As String
レビューありがとうございます。
コメントを追加いたします。

2022-09-15 08:07 UTC, danielkaneko commented on ShoppingCart/GoodsListMaker.vb
> +    Public Function RegisterGoodsList() As List(Of GoodsProperty)
レビューありがとうございます。
メソッド名をMakeに変更いたします。

2022-09-15 08:07 UTC, danielkaneko commented on ShoppingCart/ListShower.vb
> +﻿Public Class ListShower
レビューありがとうございます。
コメントを追加いたします。

2022-09-15 08:07 UTC, danielkaneko commented on ShoppingCart/ListShower.vb
> +        For Each list In goodsList
レビューありがとうございます。
型宣言の追加と機能にふさわしい変数名に修正いたします。

2022-09-15 08:07 UTC, danielkaneko commented on ShoppingCart/GoodsListMaker.vb
> +    Public Class GoodsProperty
レビューありがとうございます。
「商品」を独立させ、`GoodsProperty`をGoodsに修正いたします。

2022-09-15 08:07 UTC, danielkaneko commented on ShoppingCart/ListShower.vb
> +                          "価格：" & list.goodsPrice & "円" & vbCrLf & "在庫数：" & list.goodsInventory)
レビューありがとうございます。
ConsoleWriteLineを分ける形に修正いたします。

2022-09-15 23:39 UTC, konta3291 reviewed
DONE

2022-09-15 23:39 UTC, konta3291 commented on ShoppingCart/MeaningfulInputChecker.vb
> +    Public Function CheckInputCommand(inputCommand As String) As Boolean
[IMO] WhileNotChecKInputCommandで「
入力コマンドをチェックしていない間」となるので、メソッド名を違和感のないものに変えた方が良いかもしれないです。

2022-09-15 23:53 UTC, danielkaneko commented on ShoppingCart/MeaningfulInputChecker.vb
> +    Public Function CheckInputCommand(inputCommand As String) As Boolean
レビューありがとうございます。
メソッド名を変更いたします。

2022-09-16 00:27 UTC, nabemasamasa reviewed
done

2022-09-16 00:27 UTC, nabemasamasa commented on ShoppingCart/MeaningfulInputChecker.vb
> +    Public Function CheckInputCommand(inputCommand As String) As Boolean
[imo] `Check`は「確認する」だからこの場合「入力されたコマンドを確認する」なんだけど、`IsValid`で「有効である」の方が「入力されたコマンドが有効である」って事で戻り値のTrue/Falseがどっちの意味だかより説明的だと思う。
~[knowledge/コーディングルール.md#Boolean変数を返すメソッド](http://auto3tsv132/daniel-soft/knowledge/blob/master/VB.NET.%E3%82%B3%E3%83%BC%E3%83%87%E3%82%A3%E3%83%B3%E3%82%B0%E3%83%AB%E3%83%BC%E3%83%AB.md#21-boolean%E5%A4%89%E6%95%B0%E3%82%92%E8%BF%94%E3%81%99%E3%83%A1%E3%82%BD%E3%83%83%E3%83%89)のルールにもCheckがTrueの場合どちらの意味か分かりづらいとある~

2022-09-16 00:27 UTC, nabemasamasa commented on ShoppingCart/StringExtraction.vb
> +        Return inputContent.Split(CChar(delimiter))
`inputContent`が`Nothing`だったらエラーになりますが……後、これはSharedでいいFunctionだと思う。将来的にもインスタンスに依存する可能性のなさそうな、完結したメソッドだから。
~このくらいなら普通に呼び出し元でSplitを呼ぶ~

2022-09-16 00:27 UTC, nabemasamasa commented on ShoppingCart/Main.vb
> +            ls.ShowList(goodsList.FindAll(Function(price) Integer.Parse(amountString(0)) < price.goodsPrice AndAlso price.goodsPrice < Integer.Parse(amountString(1))))
[Q] 例えば「この金額だけで検索したい！」シチュエーションとして「--price 200」みたいな入力ってありますか？

2022-09-16 00:27 UTC, nabemasamasa commented on ShoppingCart/MeaningfulInputChecker.vb
> +        If StringUtil.IsNotEmpty(inputCommand) AndAlso "--sort price".Equals(inputCommand) Then
`--sort 名前`でワンセットだけど、今後比較したい項目が増減する度ワンセットで増えていく、`--sort`のコマンドが`--asc`とか`--desc`で昇順、降順を切り替えたいって要望が来たら1パターン×2パターン×項目数の結果の分だけIf文が作られる事になって長文になり可読性が落ちる。。。(加えて言えば、ユーザーから複数項目でソートしたいって要望が来ても破綻する)
まぁ、「要望が来た時に対応する」という事でYAGNIで良いかも知れませんが。

2022-09-16 00:27 UTC, nabemasamasa commented on ShoppingCart/Main.vb
> +            ls.ShowList(goodsList.FindAll(Function(name) name.goodsName.Contains(inputCommand.Substring(7))))
[imo] 七文字目以降で抽出してるけど、コードを読んだ時に「半角スペースでSplitした結果の第二引数」のルールだとわかるように私なら「半角スペースでSplitした結果の２番目」で書くかな

2022-09-16 00:27 UTC, nabemasamasa commented on ShoppingCart/MeaningfulInputChecker.vb
> +        IsExit = False
[imo] DoLoopの中でMeaningFulInputのインスタンスを毎回初期化すればこの「変数の初期化処理」はいらなそう。
`While True`で`exit`が入力されたら`Exit Loop`すれば、DoLoopの条件で使用してる`MeaningFulInput`もループの中に閉じ込めることが出来るし。

2022-09-16 00:31 UTC, nabemasamasa commented on ShoppingCart/StringExtraction.vb
> +        Return inputContent.Split(CChar(delimiter))
(今更だけどメソッド名`ExtractionString`って「文字列を抽出する」なんだけど、、、、うーん、、、、、、、、、)

2022-09-16 00:48 UTC, danielkaneko commented on ShoppingCart/MeaningfulInputChecker.vb
> +    Public Function CheckInputCommand(inputCommand As String) As Boolean
レビューありがとうございます。
メソッド名を修正いたします。

2022-09-16 00:48 UTC, danielkaneko commented on ShoppingCart/StringExtraction.vb
> +        Return inputContent.Split(CChar(delimiter))
レビューありがとうございます。
Nothingの場合のエラー処理の追加とSharedに変更いたします。

2022-09-16 00:48 UTC, danielkaneko commented on ShoppingCart/Main.vb
> +            ls.ShowList(goodsList.FindAll(Function(price) Integer.Parse(amountString(0)) < price.goodsPrice AndAlso price.goodsPrice < Integer.Parse(amountString(1))))
レビューありがとうございます。
現在はありませんので、確認してまいります。

2022-09-16 00:48 UTC, danielkaneko commented on ShoppingCart/MeaningfulInputChecker.vb
> +        If StringUtil.IsNotEmpty(inputCommand) AndAlso "--sort price".Equals(inputCommand) Then
レビューありがとうございます。
出題者に確認を取り、対応いたします。

2022-09-16 00:48 UTC, danielkaneko commented on ShoppingCart/Main.vb
> +            ls.ShowList(goodsList.FindAll(Function(name) name.goodsName.Contains(inputCommand.Substring(7))))
レビューありがとうございます。
「半角スペースでSplitした結果の２番目」の書き方に修正いたします。

2022-09-16 00:48 UTC, danielkaneko commented on ShoppingCart/MeaningfulInputChecker.vb
> +        IsExit = False
レビューありがとうございます。
インスタンスの初期化をループの中で行う形に修正いたします。

2022-09-16 01:47 UTC, Takatatsu9 commented on ShoppingCart/GoodsListMaker.vb
> +﻿Public Class GoodsListMaker
俺らは @danielkaneko の自動校正マシンじゃねえんだぞ。コーディングルール覚える気あんのか。

2022-09-16 01:58 UTC, danielkaneko commented on ShoppingCart/GoodsListMaker.vb
> +﻿Public Class GoodsListMaker
大変申し訳ございません。

2022-09-16 02:01 UTC, danielkaneko commented on ShoppingCart/Main.vb
> +            ls.ShowList(goodsList.FindAll(Function(price) Integer.Parse(amountString(0)) < price.goodsPrice AndAlso price.goodsPrice < Integer.Parse(amountString(1))))
確認をしたところ、不要とのことでした。

2022-09-16 02:02 UTC, Takatatsu9 reviewed
Done

2022-09-16 02:02 UTC, Takatatsu9 commented on ShoppingCart/GoodsListMaker.vb
> +        Public goodsName As String
コメントもうあるんですがそれは・・・（指摘してるのはそこじゃない）

2022-09-16 02:02 UTC, Takatatsu9 commented on ShoppingCart/GoodsListMaker.vb
> +        Public goodsName As String
[IMO] Public変数だと外部から書き換えられちゃうので、ReadOnly Propertyのほうがいいかも。
クラス内からなら書き換えられるけど、クラス外からだと書き換えられないって値が実現できます。

2022-09-16 02:02 UTC, Takatatsu9 commented on ShoppingCart/Main.vb
> +        Dim plm As New GoodsListMaker
[nits] `p`は一体どこから来たんだ・・・？

2022-09-16 02:02 UTC, Takatatsu9 commented on ShoppingCart/MeaningfulInputChecker.vb
> +    Public IsList As Boolean = False
[IMO] `IsList`だとリスト型であるって捉えられもするので、`IsListCommand`とかのほうがいいかも

2022-09-16 02:02 UTC, Takatatsu9 commented on ShoppingCart/Main.vb
> +            ls.ShowList(goodsList.FindAll(Function(price) Integer.Parse(amountString(0)) < price.goodsPrice AndAlso price.goodsPrice < Integer.Parse(amountString(1))))
もうラムダ式使えるのすごいな。私1年目か2年目でようやく理解したのに（機能は完全に理解できるまで使わない派）

2022-09-16 02:02 UTC, Takatatsu9 commented on ShoppingCart/Main.vb
> +            ls.ShowList(goodsList.FindAll(Function(price) Integer.Parse(amountString(0)) < price.goodsPrice AndAlso price.goodsPrice < Integer.Parse(amountString(1))))
[IMO] これクラス化できませんか？検索金額に一致してる商品がちゃんと取得できるかのテストがあると良いので

2022-09-16 02:02 UTC, Takatatsu9 commented on ShoppingCart.Test/ShoppingCart.Test.vbproj
> -    <NoWarn>42016,41999,42017,42018,42019,42032,42036,42020,42021,42022</NoWarn>
> 暗黙的型変換を防ぐためにプロジェクトの設定を変更

👍

2022-09-16 02:02 UTC, Takatatsu9 commented on ShoppingCart.Test/MeaningfulInputCheckerTest.vb
> +        <TestCase("--soRt price")>
[IMO] `--sort price`がTrueで`--soRt price`がFalseですが、`--sort prICe`とかだとどうなるんでしょうね

2022-09-16 02:02 UTC, Takatatsu9 commented on ShoppingCart/MeaningfulInputChecker.vb
> +        If StringUtil.IsNotEmpty(inputCommand) AndAlso "--sort price".Equals(inputCommand) Then
@danielkaneko YAGNIの意味ってわかりますか？

2022-09-16 02:04 UTC, danielkaneko commented on ShoppingCart/MeaningfulInputChecker.vb
> +        If StringUtil.IsNotEmpty(inputCommand) AndAlso "--sort price".Equals(inputCommand) Then
確認をしたところ、昇順、降順の切り替えと複数項目での並び替えの機能は必要とのことでしたので機能の追加と条件式等の修正をいたします。

2022-09-16 02:09 UTC, Takatatsu9 commented on ShoppingCart/GoodsListMaker.vb
> +﻿Public Class GoodsListMaker
コーディングルール覚えた上でちょっと抜けちゃったなら、まあしょうがないってなりますがね、
全体読んだらそんなルールは無いと言わんばかりに抜けてるんでね・・・

2022-09-16 02:12 UTC, nabemasamasa commented on ShoppingCart/GoodsListMaker.vb
> +﻿Public Class GoodsListMaker
@Takatatsu9  の指摘の言葉はだいぶ荒っぽいけど、
それはそれとして、私も私で`Public`のルールについて特に言及される事が目立つと感じているので、、、、

ここはひとつ、もう社会人な訳だし、私としては何かしら改善策を提示してほしい。

2022-09-16 02:29 UTC, danielkaneko commented on ShoppingCart/GoodsListMaker.vb
> +        Public goodsName As String
失礼いたしました。
変数名を修正いたします。

2022-09-16 02:33 UTC, danielkaneko commented on ShoppingCart/MeaningfulInputChecker.vb
> +        If StringUtil.IsNotEmpty(inputCommand) AndAlso "--sort price".Equals(inputCommand) Then
@Takatatsu9 
必要になってからその機能を付ける、必要になるまでつけるなという意味かと思います。
「要望が来た時に対応する」との指摘でしたので、出題者に質問をさせていただきました。
現段階(指摘を頂いたとき)では要望が来ているわけではないから追加の必要はないということだったのでしょうか。

2022-09-16 02:33 UTC, danielkaneko commented on ShoppingCart/GoodsListMaker.vb
> +        Public goodsName As String
レビューありがとうございます。
ReadOnly Propertyに変更いたします。

2022-09-16 02:33 UTC, danielkaneko commented on ShoppingCart/Main.vb
> +        Dim plm As New GoodsListMaker
レビューありがとうございます。
変数名を修正いたします。

2022-09-16 02:34 UTC, danielkaneko commented on ShoppingCart/MeaningfulInputChecker.vb
> +    Public IsList As Boolean = False
レビューありがとうございます。
変数名を修正いたします。

2022-09-16 02:34 UTC, danielkaneko commented on ShoppingCart/Main.vb
> +            ls.ShowList(goodsList.FindAll(Function(price) Integer.Parse(amountString(0)) < price.goodsPrice AndAlso price.goodsPrice < Integer.Parse(amountString(1))))
レビューありがとうございます。

2022-09-16 02:34 UTC, danielkaneko commented on ShoppingCart/Main.vb
> +            ls.ShowList(goodsList.FindAll(Function(price) Integer.Parse(amountString(0)) < price.goodsPrice AndAlso price.goodsPrice < Integer.Parse(amountString(1))))
レビューありがとうございます。
クラス分けいたします。

2022-09-16 02:34 UTC, danielkaneko commented on ShoppingCart.Test/ShoppingCart.Test.vbproj
> -    <NoWarn>42016,41999,42017,42018,42019,42032,42036,42020,42021,42022</NoWarn>
レビューありがとうございます。

2022-09-16 02:34 UTC, danielkaneko commented on ShoppingCart.Test/MeaningfulInputCheckerTest.vb
> +        <TestCase("--soRt price")>
レビューありがとうございます。
テスト項目を追加いたします。

2022-09-16 02:36 UTC, Takatatsu9 commented on ShoppingCart/MeaningfulInputChecker.vb
> +    Public Function CheckInputCommand(inputCommand As String) As Boolean
「正しいかチェックする」系は、我々はValidate〜ってメソッド名にしてますね。正しければTrueです。

2022-09-16 02:36 UTC, Takatatsu9 commented on ShoppingCart/MeaningfulInputChecker.vb
> +        If StringUtil.IsNotEmpty(inputCommand) AndAlso "--sort price".Equals(inputCommand) Then
はい、その通りです 👍

2022-09-16 02:51 UTC, danielkaneko commented on ShoppingCart/GoodsListMaker.vb
> +﻿Public Class GoodsListMaker
Publicのルールにつきましては、あたらしくクラス等を追加する際、例`コーディングルールにのっとり、コメントの追加`のようにコミットに残す形で改善をさせていただきます。

改めまして申し訳ございませんでした。

2022-09-16 02:51 UTC, danielkaneko commented on ShoppingCart/MeaningfulInputChecker.vb
> +    Public Function CheckInputCommand(inputCommand As String) As Boolean
ありがとうございます。

2022-09-16 03:04 UTC, nabemasamasa commented on ShoppingCart/GoodsListMaker.vb
> +﻿Public Class GoodsListMaker
外部参照可能なPublicな変数/Propertyをつい小文字にしちゃうのも`コーディングルールにのっとり、変数を頭大文字にする`をコミットするんです？

2022-09-16 03:46 UTC, Takatatsu9 commented on ShoppingCart/GoodsListMaker.vb
> +﻿Public Class GoodsListMaker
なんか、 @nabemasamasa は「今後同じミスをしないよう再発防止策を言ってほしい」に対して
@danielkaneko は「次の作業内容」を返したように見えるけど…

2022-09-16 04:23 UTC, Takatatsu9 commented on ShoppingCart/GoodsListMaker.vb
> +    Public Class GoodsProperty
米Amazon見てみたんですけど、商品は「products」って単語使われてましたね

2022-09-16 04:24 UTC, Takatatsu9 commented on ShoppingCart/GoodsListMaker.vb
> +    ''' 所品リストのプロパティ設定
あっ、typo

2022-09-16 04:37 UTC, danielkaneko commented on ShoppingCart/GoodsListMaker.vb
> +    ''' 所品リストのプロパティ設定
レビューありがとうございます。
修正いたします。

2022-09-16 06:00 UTC, danielkaneko commented on ShoppingCart/GoodsListMaker.vb
> +﻿Public Class GoodsListMaker
今日中に改善案を提示できるよう努めます。
今日中に提示できそうになければその旨をまたお伝えさせていただきます。
（現在、Publicな変数の頭小文字にしてしまう問題の改善策は見つかったが、コメントのし忘れについては改善策が見つかっていない状況。）

2022-09-16 06:17 UTC, danielkaneko commented on ShoppingCart/GoodsListMaker.vb
> +    Public Class GoodsProperty
米Amazonに倣い、GoodsをProductsに変更いたします。

2022-09-16 07:51 UTC, danielkaneko commented on ShoppingCart/GoodsListMaker.vb
> +﻿Public Class GoodsListMaker
改善案

- 外部参照可能なPublicな変数/Propertyを頭小文字にしてしまう問題についてはVisualStudioのコードスタイルの設定にて、パスカルケースを満たしていない場合エラーになるよう設定
- コメントの忘れについてはgit hooksを用いて、コミットの際にコメント忘れがないかどうかの注意喚起を行う(これだけでは不十分かもしれないが、git hooksを用いる案以上のものが見つからなかったため現状の案とする。現在も新たな改善案を模索している。)

上記をもって改善案とさせていただきます。

2022-09-20 06:40 UTC, Takatatsu9 reviewed
Done

2022-09-20 06:40 UTC, Takatatsu9 commented on ShoppingCart/Products.vb
> +Public Class Products
> 商品を意味する英語をgoodsからproductsに変更

1つ前の`Goods`クラス作るときからこの名前にすればよかったのに。
これを二度手間と呼びます。

2022-09-20 06:40 UTC, Takatatsu9 commented on ShoppingCart/MeaningfulInputChecker.vb
> +    Public Function IsValidInputCommand(inputCommand As String) As Boolean
[IMO] `Validate〜`のほうがいいと思う。コメント的にも。
（あれ？前言ったときも`Validate〜`って紹介してたはずなんだけど）

2022-09-20 06:40 UTC, Takatatsu9 commented on ShoppingCart.Test/ReturningListInResponseToCommandTest.vb
> +    End Sub
[IMO] Falseになるパターンのテストが無いと、どんな条件だろうと全部Trueの可能性も否定できない

2022-09-20 06:40 UTC, Takatatsu9 commented on ShoppingCart/SplittingString.vb
> +        End If
[IMO] `文字列.Split`もNULLなら例外返すし、このラップメソッド自体無駄では？
むしろこのメソッドを呼ぶ前のところでNULLチェックしたほうがいい。

2022-09-20 06:40 UTC, Takatatsu9 commented on ShoppingCart/Products.vb
> +    ReadOnly Property ProductsName As String
[Q] なんでアクセス修飾子消しちゃうんですか

2022-09-20 06:40 UTC, Takatatsu9 commented on ShoppingCart/Main.vb
> +        Dim rlirtc As New ReturningListInResponseToCommand
[IMO] 最早何を意味してるのかまるでわからない変数名

2022-09-20 06:40 UTC, Takatatsu9 commented on ShoppingCart/ReturningListInResponseToCommand.vb
> +        Return (From products In productsList Order By products.ProductsName, products.ProductsDescription, products.ProductsPrice, products.ProductsInventory).ToList()
この書き方よくわからないから`コレクション型.OrderBy(Function(変数名) 〜)`って形がいいんだけど
OrderByの場合だと他のLINQと書き方が違ったような気がするから書き方がわからん

2022-09-20 08:03 UTC, danielkaneko commented on ShoppingCart/Products.vb
> +Public Class Products
レビューありがとうございます。

2022-09-20 08:06 UTC, nabemasamasa commented on ShoppingCart/ReturningListInResponseToCommand.vb
> +        Return (From products In productsList Order By products.ProductsName, products.ProductsDescription, products.ProductsPrice, products.ProductsInventory).ToList()
OrderByだと、二つ目以降の指定はThenByで呼ばないとダメ。(`OrderBy().ThenBy().ThenBy......`)
クエリ形式の方だと、ThenByじゃなくてそのままカンマで繋げられるっぽい………。

ただ今回CompareでCultureInfoを指定しないとテスト通らなくて、そうなるとクエリ形式でCompareをどうやって当てるかは私も書き方わからないや。

2022-09-20 08:14 UTC, danielkaneko commented on ShoppingCart/MeaningfulInputChecker.vb
> +    Public Function IsValidInputCommand(inputCommand As String) As Boolean
@konta3291 よりの指摘で英文として違和感がなくなるように、とのことでしたのでIsValidにいたしました。
メソッドのコメント的には`Validate`のほうがおっしゃる通り適切かと思いますので修正いたします。

2022-09-20 08:18 UTC, danielkaneko commented on ShoppingCart.Test/ReturningListInResponseToCommandTest.vb
> +    End Sub
レビューありがとうございます。
テストするメソッドがBoolean型でないので適切でなかったテストメソッド名を修正させていただきます。
Falseになるテストパターンの追加は必要でしょうか？

2022-09-20 08:18 UTC, danielkaneko commented on ShoppingCart/SplittingString.vb
> +        End If
レビューありがとうございます。
Nullチェック個所を修正いたします。

2022-09-20 08:21 UTC, danielkaneko commented on ShoppingCart/Products.vb
> +    ReadOnly Property ProductsName As String
レビューありがとうございます。
申し訳ございません。`ReadOnly Property`を追加した際誤って消してしまいました。
修正いたします。

2022-09-20 08:21 UTC, danielkaneko commented on ShoppingCart/Main.vb
> +        Dim rlirtc As New ReturningListInResponseToCommand
レビューありがとうございます。
変数名を修正いたします。

2022-09-20 08:22 UTC, danielkaneko commented on ShoppingCart/ReturningListInResponseToCommand.vb
> +        Return (From products In productsList Order By products.ProductsName, products.ProductsDescription, products.ProductsPrice, products.ProductsInventory).ToList()
レビューありがとうございます。
`コレクション型.OrderBy(Function(変数名) 〜)`の書き方に修正いたします。

2022-09-20 08:25 UTC, nabemasamasa reviewed
done

2022-09-20 08:25 UTC, nabemasamasa commented on ShoppingCart/Products.vb
> +    Public ProductsName As String
> 商品を意味する英語をgoodsからproductsに変更

こういう時にRenameの影響が増えるから、私はプロパティの名前にクラス名はつけたくない。
`クラス名がわかる変数名`.`プロパティ名`でコーディングすれば、「何の」名前、「何の」説明かはすぐわかる

2022-09-20 08:25 UTC, nabemasamasa commented on ShoppingCart/SplittingString.vb
> +        If IsNothing(inputContent) Then
[Q] なんで、このメソッドを作りたかったんでしたっけ？
パッと見、VB.NETに実装済みの`Split`メソッドをそのままWrapしただけのメソッド。
たぶん、そうしなければならなかった、そうしたかったという、「実装者の想い」があるはず。

2022-09-20 08:25 UTC, nabemasamasa commented on ShoppingCart/Main.vb
> +                ls.ShowList(productsList.FindAll(Function(name) name.ProductsName.Contains(SplittingString.SplitIntoArrays(inputCommand, " ")(1))))
[imo] `FindAll`が内部的に`List`の中の要素に対して、一回一回`Function`で定義した内容を実行する。
と、するとこのSplitも毎回実行される。
私なら、外側に変数を定義して、その変数を参照させることでSplitを一回だけ実行されるようにする。

2022-09-20 23:46 UTC, danielkaneko commented on ShoppingCart/Products.vb
> +    Public ProductsName As String
レビューありがとうございます。
`Products.Name`のほうが簡潔でわかりやすいのでプロパティ名を修正いたします。

2022-09-20 23:46 UTC, danielkaneko commented on ShoppingCart/Main.vb
> +                ls.ShowList(productsList.FindAll(Function(name) name.ProductsName.Contains(SplittingString.SplitIntoArrays(inputCommand, " ")(1))))
レビューありがとうございます。
Split結果を変数に入れて参照する形に修正いたします。

2022-09-20 23:53 UTC, Takatatsu9 commented on ShoppingCart/MeaningfulInputChecker.vb
> +    Public Function IsValidInputCommand(inputCommand As String) As Boolean
なぜ`Validate`のほうが適切だと思ったのですか？

2022-09-20 23:55 UTC, Takatatsu9 commented on ShoppingCart.Test/ReturningListInResponseToCommandTest.vb
> +    End Sub
あー、そういうテストか。ならこのテスト方法自体が適切じゃない。
`Assert.That(actual, [Is].EqualTo(expected))`を使ってください。

2022-09-20 23:58 UTC, Takatatsu9 commented on ShoppingCart/Products.vb
> +Public Class Products
次からも気をつけるつもりはないと…

2022-09-21 00:10 UTC, danielkaneko commented on ShoppingCart/SplittingString.vb
> +        If IsNothing(inputContent) Then
レビューありがとうございます。
商品価格検索の際にsplitを複数回使用しまして、メソッドに分けたほうが個人的にコードが見やすいと感じたためメソッドを作りました。

2022-09-21 00:23 UTC, danielkaneko commented on ShoppingCart/MeaningfulInputChecker.vb
> +    Public Function IsValidInputCommand(inputCommand As String) As Boolean
`IsValidInputCommand`の和訳は「有効な入力コマンドです」
`ValidateInputCommand`の和訳は「入力コマンドの検証」
メソッドのコメントは「入力された内容がコマンドとして正しいかチェックする」と`ValidateInputCommand`の和訳に近いと思ったため`Validate`のほうが適切だと思いました。

2022-09-21 00:23 UTC, danielkaneko commented on ShoppingCart.Test/ReturningListInResponseToCommandTest.vb
> +    End Sub
承知いたしました。

2022-09-21 00:24 UTC, nabemasamasa commented on ShoppingCart/SplittingString.vb
> +        If IsNothing(inputContent) Then
だとしたら、「意味」での命名と、「商品価格検索」のクラス内にこのメソッドを置いた方が、よりわかりやすいと思う。
今は`ShoppingCart`プロジェクトの直下という大海に、`SplittingString`がいる。
命名を見た際に「文字列分割する為のクラスなんだな」という情報が取れる、、、が中身を見るとSplitしてるだけ、他の人がこのプロジェクトに携わるとしたらこのメソッドをわざわざ使わないんじゃないかな。

2022-09-21 00:45 UTC, danielkaneko commented on ShoppingCart/SplittingString.vb
> +        If IsNothing(inputContent) Then
ありがとうございます。
配列に分けるメソッドを「商品価格検索」のクラス内に移動させる形で修正いたします。

2022-09-21 01:33 UTC, konta3291 reviewed
Done

2022-09-21 01:33 UTC, konta3291 commented on ShoppingCart/Main.vb
>              If mic.IsSearchName Then
明確な解決策がないので指摘ではなくコメントなのですが、Mainであるここでコマンド毎の処理を行うためにIFで聞くと、今後コマンドが追加される毎に下に長くなってしまいますね。

2022-09-21 01:35 UTC, konta3291 commented on ShoppingCart/Main.vb
> +                ls.ShowList(rlirtc.ReturnSearchNameList(inputCommand, productsList))
明確な解決策がないので指摘ではなくコメントなのですが、Mainであるここでコマンド毎の処理を行うためにIFで聞くと、今後コマンドが追加される毎に下に長くなってしまいますね。

2022-09-21 01:51 UTC, danielkaneko commented on ShoppingCart/Main.vb
> +                ls.ShowList(rlirtc.ReturnSearchNameList(inputCommand, productsList))
レビューありがとうございます。
確かに長くなってしまいそうなので今のうちから解決策を模索しようと思います。

2022-09-21 07:20 UTC, danielkaneko commented on ShoppingCart/Main.vb
> +                ls.ShowList(productsList.FindAll(Function(name) name.ProductsName.Contains(SplittingString.SplitIntoArrays(inputCommand, " ")(1))))
修正いたしました。
コミットハッシュ： b4871d2

2022-09-21 07:20 UTC, danielkaneko commented on ShoppingCart/SplittingString.vb
> +        If IsNothing(inputContent) Then
修正いたしました。
コミットハッシュ： 1a14fa3

2022-09-21 07:20 UTC, danielkaneko commented on ShoppingCart/Products.vb
> +    Public ProductsName As String
修正いたしました。
コミットハッシュ： 48a178e

2022-09-21 07:20 UTC, danielkaneko commented on ShoppingCart/ReturningListInResponseToCommand.vb
> +        Return (From products In productsList Order By products.ProductsName, products.ProductsDescription, products.ProductsPrice, products.ProductsInventory).ToList()
修正いたしました。
コミットハッシュ： 36b5d9a

2022-09-21 07:20 UTC, danielkaneko commented on ShoppingCart/Main.vb
> +        Dim rlirtc As New ReturningListInResponseToCommand
修正いたしました。
コミットハッシュ： 288659c

2022-09-21 07:20 UTC, danielkaneko commented on ShoppingCart/Products.vb
> +    ReadOnly Property ProductsName As String
修正いたしました。
コミットハッシュ： 0790549

2022-09-21 07:20 UTC, danielkaneko commented on ShoppingCart/SplittingString.vb
> +        End If
修正いたしました。
コミットハッシュ： eb4576e

2022-09-21 07:20 UTC, danielkaneko commented on ShoppingCart.Test/ReturningListInResponseToCommandTest.vb
> +    End Sub
修正いたしました。
コミットハッシュ： a7afb4b

2022-09-21 07:20 UTC, danielkaneko commented on ShoppingCart/MeaningfulInputChecker.vb
> +    Public Function IsValidInputCommand(inputCommand As String) As Boolean
修正いたしました。
コミットハッシュ： ea13f8f

2022-09-21 07:35 UTC, Takatatsu9 reviewed
Done

2022-09-21 07:35 UTC, Takatatsu9 commented on ShoppingCart.Test/ReturningListInResponseToCommandTest.vb
> +        Assert.That(actual(actual.Count - 1).ProductsName, [Is].EqualTo("掃除機"))
なんで上のテストのインデックスは絶対値なのにここから下のはCount-1なんだ・・・

2022-09-21 07:35 UTC, Takatatsu9 commented on ShoppingCart/ReturningListInResponseToCommand.vb
> -        End If
ここ消したらいよいよこのメソッド(`SplitCommandIntoArrays`)の存在意義がなくなる

2022-09-21 07:35 UTC, Takatatsu9 commented on ShoppingCart/Main.vb
> +        Dim returningListInResponseToCommand As New ReturningListInResponseToCommand
[IMO] 長過ぎる・・・もっと省略できません？

2022-09-21 07:35 UTC, Takatatsu9 commented on ShoppingCart/ReturningListInResponseToCommand.vb
> +        Return productsList.OrderBy(Function(products) products.ProductsName).ThenBy(Function(products) products.ProductsDescription).ThenBy(Function(products) products.ProductsPrice).ThenBy(Function
[IMO] この`products`なんですけど、コレクション型じゃなくて単体になってるので複数形じゃないほうがいいです

2022-09-21 07:35 UTC, Takatatsu9 commented on ShoppingCart/ReturningListInResponseToCommand.vb
> +        Return productsList.FindAll(Function(name) name.Name.Contains(stringToSearch))
[IMO] `name`じゃなくて`product`が適切だと思う。
ここの`name`の中身は`productsList`の中を1個ずつ取り出したものが入るので。

2022-09-21 07:35 UTC, Takatatsu9 commented on ShoppingCart/ReturningListInResponseToCommand.vb
> +        Dim pnc As New ProductsNameCompare
[IMO] 意味のわからん変数名は極力使わないようにしてほしいなあ。
コーディングルールではスコープが短ければ許容してるけど、
そればっかだと癖になるから（実際どこでも使いまくってるし）。
`compare`がとてもシンプルでとてもわかりやすい変数名じゃないかな。

2022-09-21 07:35 UTC, Takatatsu9 commented on ShoppingCart/ReturningListInResponseToCommand.vb
> +        Public Function Compare(x As String, y As String) As Integer Implements IComparer(Of String).Compare
[MUST] Public・・・？
![築地魚河岸三代目](https://user-images.githubusercontent.com/50448373/191443385-0ab860aa-d591-4419-af13-b54fcbabf9dc.jpg)

2022-09-21 07:45 UTC, nabemasamasa commented on ShoppingCart/ReturningListInResponseToCommand.vb
> +        Public Function Compare(x As String, y As String) As Integer Implements IComparer(Of String).Compare
Privateクラスや

2022-09-21 07:46 UTC, Takatatsu9 commented on ShoppingCart/ReturningListInResponseToCommand.vb
> +        Public Function Compare(x As String, y As String) As Integer Implements IComparer(Of String).Compare
Privateクラス内ならいいってルールでしたっけ・・・

2022-09-21 07:50 UTC, Takatatsu9 commented on ShoppingCart/ReturningListInResponseToCommand.vb
> +        Public Function Compare(x As String, y As String) As Integer Implements IComparer(Of String).Compare
@danielkaneko 一旦この件は保留で

2022-09-21 07:59 UTC, Takatatsu9 commented on ShoppingCart/ReturningListInResponseToCommand.vb
> +        Public Function Compare(x As String, y As String) As Integer Implements IComparer(Of String).Compare
ああ、Interfaceのメソッドか、じゃあOKですね。

2022-09-21 08:09 UTC, danielkaneko commented on ShoppingCart.Test/ReturningListInResponseToCommandTest.vb
> +        Assert.That(actual(actual.Count - 1).ProductsName, [Is].EqualTo("掃除機"))
レビューありがとうございます。
上のテストは検索結果のリストの項目数が少ないので絶対値にし、並び替えはリストの項目数が多いのでリストの最初と最後を参照するためにCount-1のような書き方にいたしました。

2022-09-21 08:09 UTC, danielkaneko commented on ShoppingCart/ReturningListInResponseToCommand.vb
> -        End If
レビューありがとうございます。
私が個人的に見やすいと感じたためメソッドを作成したのですが、確かにこのメソッドはなくてもいいようにも思えますので修正いたします。

2022-09-21 08:09 UTC, danielkaneko commented on ShoppingCart/Main.vb
> +        Dim returningListInResponseToCommand As New ReturningListInResponseToCommand
レビューありがとうございます。
変数名を修正いたします。

2022-09-21 08:09 UTC, danielkaneko commented on ShoppingCart/ReturningListInResponseToCommand.vb
> +        Return productsList.OrderBy(Function(products) products.ProductsName).ThenBy(Function(products) products.ProductsDescription).ThenBy(Function(products) products.ProductsPrice).ThenBy(Function
レビューありがとうございます。
`products`を`product`に修正いたします。

2022-09-21 08:09 UTC, danielkaneko commented on ShoppingCart/ReturningListInResponseToCommand.vb
> +        Return productsList.FindAll(Function(name) name.Name.Contains(stringToSearch))
レビューありがとうございます。
`name`を`product`に修正いたします。

2022-09-21 08:09 UTC, danielkaneko commented on ShoppingCart/ReturningListInResponseToCommand.vb
> +        Dim pnc As New ProductsNameCompare
レビューありがとうございます。
変数名を修正し、今後そのような変数名を使わないようにいたします。

2022-09-22 05:29 UTC, konta3291 reviewed
Done

2022-09-22 05:29 UTC, konta3291 commented on ShoppingCart/ReturningListInResponseToCommand.vb
> +        Dim stringToSearch As String = SplitCommandIntoArrays(inputCommand, " ")(1)
[Q]よくわからないだけなのですが、SplitCommandIntoArrays(inputCommand, " ")(1)の(1)って何を表しているのでしょうか。
調べてもわからなかったため、可能でしたらお時間があるときに教えていただきたいです。

2022-09-22 05:46 UTC, danielkaneko commented on ShoppingCart/ReturningListInResponseToCommand.vb
> +        Dim stringToSearch As String = SplitCommandIntoArrays(inputCommand, " ")(1)
レビューありがとうございます。
SplitCommandIntoArraysメソッドが返す値がリストなので、要素の番号指定の(1)になります。

2022-09-22 05:57 UTC, konta3291 commented on ShoppingCart/ReturningListInResponseToCommand.vb
> +        Dim stringToSearch As String = SplitCommandIntoArrays(inputCommand, " ")(1)
ご回答ありがとうございます。
わかりました、教えてくださりありがとうございます。

2022-09-22 06:14 UTC, danielkaneko commented on ShoppingCart/ReturningListInResponseToCommand.vb
> -        End If
修正いたしました。
コミットハッシュ： bdf1c41

2022-09-22 06:14 UTC, danielkaneko commented on ShoppingCart/Main.vb
> +        Dim returningListInResponseToCommand As New ReturningListInResponseToCommand
修正いたしました。
コミットハッシュ： 20369b8

2022-09-22 06:14 UTC, danielkaneko commented on ShoppingCart/ReturningListInResponseToCommand.vb
> +        Return productsList.OrderBy(Function(products) products.ProductsName).ThenBy(Function(products) products.ProductsDescription).ThenBy(Function(products) products.ProductsPrice).ThenBy(Function
修正いたしました。
コミットハッシュ： 5c6576a

2022-09-22 06:14 UTC, danielkaneko commented on ShoppingCart/ReturningListInResponseToCommand.vb
> +        Return productsList.FindAll(Function(name) name.Name.Contains(stringToSearch))
修正いたしました。
コミットハッシュ： 5c86b81

2022-09-22 06:14 UTC, danielkaneko commented on ShoppingCart/ReturningListInResponseToCommand.vb
> +        Dim pnc As New ProductsNameCompare
修正いたしました。
コミットハッシュ： 6446c1a

2022-09-22 07:18 UTC, Takatatsu9 reviewed
Done

2022-09-22 07:18 UTC, Takatatsu9 commented on ShoppingCart/ReturningListInResponseToCommand.vb
> +        Dim stringToSearch As String = inputCommand.Split(CChar(" "))(1)
[IMO] たしか`CChar`使わなくても1文字というか1byte文字なら`" "c`みたいな書き方でChar型にできたと思う。
あとChar型変換しなくても分割文字に使えたような使えなかったような…、どうだったかな。

2022-09-22 07:18 UTC, Takatatsu9 commented on ShoppingCart/Main.vb
> +        Dim returningList As New ReturningListInResponseToCommand
[IMO] Listだとコレクション型に見える（変数名にListを入れてコレクション型を示す方法は不適切だけど）。
そもそもの問題としてクラス名が長すぎるというか機能を表す言葉が
複数の単語から成り立ってるせいで適切な省略名に悩むのでは？

2022-09-22 07:47 UTC, danielkaneko commented on ShoppingCart/ReturningListInResponseToCommand.vb
> +        Dim stringToSearch As String = inputCommand.Split(CChar(" "))(1)
レビューありがとうございます。
Char型に変換をしないと分割文字に使用できませんでした。
`" "c`の書き方に修正いたします。

2022-09-22 07:48 UTC, danielkaneko commented on ShoppingCart/Main.vb
> +        Dim returningList As New ReturningListInResponseToCommand
レビューありがとうございます。
クラス名を修正し、それに合わせ変数名も修正いたします。

2022-09-22 23:26 UTC, konta3291 reviewed
Done

2022-09-23 00:31 UTC, nabemasamasa commented on ShoppingCart.Test/ReturningListInResponseToCommandTest.vb
> +        Assert.That(actual(actual.Count - 1).ProductsName, [Is].EqualTo("掃除機"))
最初と最後を参照したいと聞いて、CollectionならFirstとLastが使えるよ

2022-09-23 00:48 UTC, danielkaneko commented on ShoppingCart.Test/ReturningListInResponseToCommandTest.vb
> +        Assert.That(actual(actual.Count - 1).ProductsName, [Is].EqualTo("掃除機"))
ありがとうございます。
最初と最後の参照をFirstとLastに変更いたします。

2022-09-23 00:52 UTC, Takatatsu9 commented on ShoppingCart.Test/ReturningListInResponseToCommandTest.vb
> +        Assert.That(actual(actual.Count - 1).ProductsName, [Is].EqualTo("掃除機"))
いやこれテストとしては27行目のexpectedや29行目のインデックスは絶対値にしなきゃダメだと思う・・・

2022-09-23 01:01 UTC, danielkaneko commented on ShoppingCart.Test/ReturningListInResponseToCommandTest.vb
> +        Assert.That(actual(actual.Count - 1).ProductsName, [Is].EqualTo("掃除機"))
それはなぜでしょうか？

2022-09-23 01:05 UTC, Takatatsu9 commented on ShoppingCart.Test/ReturningListInResponseToCommandTest.vb
> +        Assert.That(actual(actual.Count - 1).ProductsName, [Is].EqualTo("掃除機"))
テストに使用するデータをそのまま想定する値として使った場合、
想定した結果ではないにも関わらず偶然一致してたから通ったということがありえるからです

2022-09-23 01:08 UTC, danielkaneko commented on ShoppingCart.Test/ReturningListInResponseToCommandTest.vb
> +        Assert.That(actual(actual.Count - 1).ProductsName, [Is].EqualTo("掃除機"))
ありがとうございます。
インデックスを絶対値に修正いたします。

2022-09-23 01:37 UTC, nabemasamasa reviewed
Done

2022-09-23 01:37 UTC, nabemasamasa commented on ShoppingCart/ReturningListInResponseToCommand.vb
> +            Throw New ArgumentException("inputContentに値が存在しません")
変数名変わったのにExceptionの中の文字が変わってない。
[imo] 私なら、埋め込み補間式を使いつつ、さらにNameOfで変数名を取得して、いちいち文字列修正しなくても良いようにする。

2022-09-23 01:37 UTC, nabemasamasa commented on ShoppingCart/ReturningListInResponseToCommand.vb
> +    Public Shared Function SplitCommandIntoArrays(inputCommand As String, delimiter As String) As String()
[nits] 後でCCharするなら引数の型をChar型にしてもいいのでは？

2022-09-23 01:37 UTC, nabemasamasa commented on ShoppingCart/ReturningListInResponseToCommand.vb
> +    Public Shared Function SplitCommandIntoArrays(inputCommand As String, delimiter As String) As String()
[nits] このクラス以外で使わないなら、Privateで良さそう

2022-09-23 01:37 UTC, nabemasamasa commented on ShoppingCart/ReturningListInResponseToCommand.vb
> -        Dim stringToSearch As String = SplitCommandIntoArrays(inputCommand, " ")(1)
[imo] ……私なら、「引数として分割する」「引数を期間(もしくは範囲？)として分割する」で二種類メソッドを作って、中身は`Split(command, " "c)`と`Split(command, "-"c)`で区切り文字を隠ぺいする……。
コマンドの分割用文字列、全部共通だしね……。

2022-09-23 01:37 UTC, nabemasamasa commented on ShoppingCart/Main.vb
> +            If inputChecker.IsListCommand Then
[imo] ……これ、判断が長い問題ってポリモーフィズムで解決できるんじゃないかなぁ……。
まさしく、ファクトリメソッドが使えるところだと思うけど……。
「自分自身を実行すべきコマンドかどうか」と「コマンドで処理を実行する」メソッドを持つInterfaceがあって、
各機能ごとのクラスがそのInterfaceをImplementsしていて、ファクトリメソッド内では以下みたいな感じで必要なクラスを返してくれる
```vb
Function コマンドに対して動作クラスを返す(入力されたコマンド As String) As 動作用のInterface
For 動作 As 動作用のInterface In {new InterfaceをImplementsした動作クラスA, new InterfaceをImplementsした動作クラスB...}
If 動作.自分自身を実行すべきコマンドかどうか(入力されたコマンド) Then
Return 動作
End If
Next
Return Nothing
End Function

動作 As 動作用のInterface = コマンドに対して動作クラスを返す(入力されたコマンド)
If 動作 IsNot Nothing Then
動作.コマンドで処理を実行する(入力されたコマンド)
End If
```
で、Factoryメソッドについては、既に海戦ゲームで @danielkaneko さん自身が指摘したコメントに対して @konta3291  さんが対応してるので、 @konta3291  「聞かれたら」フォローお願いしてもいいかな？

2022-09-23 01:40 UTC, nabemasamasa commented on ShoppingCart/ReturningListInResponseToCommand.vb
> +    Public Shared Function SplitCommandIntoArrays(inputCommand As String, delimiter As String) As String()
後のコミットで消えてたのでmark Resolve

2022-09-23 01:40 UTC, nabemasamasa commented on ShoppingCart/ReturningListInResponseToCommand.vb
> +    Public Shared Function SplitCommandIntoArrays(inputCommand As String, delimiter As String) As String()
後のコミットで消えてたのでmark Resolve

2022-09-23 01:41 UTC, nabemasamasa commented on ShoppingCart/ReturningListInResponseToCommand.vb
> +            Throw New ArgumentException("inputContentに値が存在しません")
後のコミットでNullチェックの場所は変わってたけど、これはその場所でも使えるはず。。。。

2022-09-23 01:53 UTC, konta3291 commented on ShoppingCart/Main.vb
> +            If inputChecker.IsListCommand Then
かしこまりました。

2022-09-23 02:44 UTC, danielkaneko commented on ShoppingCart/Main.vb
> +            If inputChecker.IsListCommand Then
レビューありがとうございます。
私も指摘を頂いた方法で解決できると考えておりまして。
以前 @konta3291 よりFactoryメソッドについて参考にしたサイトを教えていただき現在勉強中ですので、わからないところ等がありましたらまた @konta3291 に質問させていただきます。
@konta3291 その時はよろしくお願いします。

2022-09-23 02:44 UTC, danielkaneko commented on ShoppingCart/ReturningListInResponseToCommand.vb
> -        Dim stringToSearch As String = SplitCommandIntoArrays(inputCommand, " ")(1)
レビューありがとうございます。
分割するだけのメソッドの作成はSplitを直接使ったほうがコードが短く収まると考えたのですが、頂いた指摘の区切り文字の隠ぺいを行ったほうが見やすくなるということでしょうか？

2022-09-23 02:44 UTC, danielkaneko commented on ShoppingCart/ReturningListInResponseToCommand.vb
> +            Throw New ArgumentException("inputContentに値が存在しません")
レビューありがとうございます。
埋め込み補間式修正を使う形で修正いたします。

2022-09-23 02:55 UTC, konta3291 commented on ShoppingCart/Main.vb
> +            If inputChecker.IsListCommand Then
かしこまりました、よろしくお願いします。

2022-09-23 03:15 UTC, nabemasamasa commented on ShoppingCart/ReturningListInResponseToCommand.vb
> -        Dim stringToSearch As String = SplitCommandIntoArrays(inputCommand, " ")(1)
いろんなところで同じ区切り文字を使っている事への共通化です。
後、処理を切り出してメソッド名というラベルを付ける事で「名前に情報を詰め込む」ことを狙ってます。
「リーダブルコード」の2章なんだけど……。

2022-09-23 04:34 UTC, danielkaneko commented on ShoppingCart/ReturningListInResponseToCommand.vb
> -        Dim stringToSearch As String = SplitCommandIntoArrays(inputCommand, " ")(1)
ありがとうございます。
今後も同じ区切り文字を使った分割を行うと思いますのでメソッドを追加いたします。

2022-09-26 07:05 UTC, danielkaneko commented on ShoppingCart.Test/ReturningListInResponseToCommandTest.vb
> +        Assert.That(actual(actual.Count - 1).ProductsName, [Is].EqualTo("掃除機"))
修正いたしました。
コミットハッシュ： c1d05fe

2022-09-26 07:05 UTC, danielkaneko commented on ShoppingCart/ReturningListInResponseToCommand.vb
> +        Dim stringToSearch As String = inputCommand.Split(CChar(" "))(1)
修正いたしました。
コミットハッシュ： 705e3f0

2022-09-26 07:05 UTC, danielkaneko commented on ShoppingCart/Main.vb
> +        Dim returningList As New ReturningListInResponseToCommand
修正いたしました。
コミットハッシュ： 8b202c5

2022-09-26 07:05 UTC, danielkaneko commented on ShoppingCart/ReturningListInResponseToCommand.vb
> +            Throw New ArgumentException("inputContentに値が存在しません")
修正いたしました。
コミットハッシュ： 6f32771

2022-09-26 07:05 UTC, danielkaneko commented on ShoppingCart/ReturningListInResponseToCommand.vb
> -        Dim stringToSearch As String = SplitCommandIntoArrays(inputCommand, " ")(1)
修正いたしました。
コミットハッシュ： 1e54482

2022-09-26 07:05 UTC, danielkaneko commented on ShoppingCart/Main.vb
> +            If inputChecker.IsListCommand Then
修正いたしました。
コミットハッシュ： 8a1b315

2022-09-26 08:04 UTC, konta3291 reviewed
Done

2022-09-26 08:04 UTC, konta3291 commented on ShoppingCart/ListShower.vb
>              For Each oneProducts As Products In productsList
[nits]oneなのに複数形の「s」がついているのは紛らわしいと思うので必要ないかと思います。

2022-09-27 00:01 UTC, danielkaneko commented on ShoppingCart/ListShower.vb
>              For Each oneProducts As Products In productsList
レビューありがとうございます。
変数名を修正いたします。

2022-09-27 00:41 UTC, nabemasamasa reviewed
Done！

2022-09-27 00:41 UTC, nabemasamasa commented on ShoppingCart/CommandDetector.vb
> +    Private Function SplittingCommand(inputCommand As String) As String()
[Q] `Splitting` って動詞です？

2022-09-27 00:51 UTC, danielkaneko commented on ShoppingCart/CommandDetector.vb
> +    Private Function SplittingCommand(inputCommand As String) As String()
レビューありがとうございます。
`splitting`は「分割」と名詞になっていますので修正いたします。

2022-09-27 01:44 UTC, danielkaneko commented on ShoppingCart/ListShower.vb
>              For Each oneProducts As Products In productsList
修正いたしました。
コミットハッシュ： 3f3f0c5

2022-09-27 01:44 UTC, danielkaneko commented on ShoppingCart/CommandDetector.vb
> +    Private Function SplittingCommand(inputCommand As String) As String()
修正いたしました。
コミットハッシュ： d590851

2022-09-27 01:48 UTC, konta3291 reviewed
DONE

2022-09-27 06:22 UTC, nabemasamasa reviewed
Done 👍

2022-09-30 05:05 UTC, Takatatsu9 reviewed
Done

2022-09-30 05:05 UTC, Takatatsu9 commented on ShoppingCart/ProductsListMaker.vb
> +            New Products("MPN-1", "消しゴム", "モノけし", 120, 30),
[IMO] 商品リストの管理はList型じゃなくてDictionary型がいいかも。
KeyにIDを入れればID被りをエラーにしてくれる。

2022-09-30 05:15 UTC, danielkaneko commented on ShoppingCart/ProductsListMaker.vb
> +            New Products("MPN-1", "消しゴム", "モノけし", 120, 30),
レビューありがとうございます。
リスト管理をDictionary型で行うよう変更いたします

2022-10-03 06:05 UTC, danielkaneko commented on ShoppingCart/ProductsListMaker.vb
> +            New Products("MPN-1", "消しゴム", "モノけし", 120, 30),
修正いたしました。
コミットハッシュ： 3a04e52

2022-10-03 06:12 UTC, Takatatsu9 reviewed
Done

2022-10-03 06:12 UTC, Takatatsu9 commented on ShoppingCart.Test/CommandDetectorTest.vb
> +        Assert.That(actual.Values(1).Name, [Is].EqualTo("鉛筆"))
[IMO] Dictionary型って`.Values`つけなくても同じように使えなかったっけ？

2022-10-03 06:12 UTC, Takatatsu9 commented on ShoppingCart/ProductsListMaker.vb
> +        Return productsList.ToDictionary(Of String, Products)(Function(keyProducts) keyProducts.Id, Function(valueProducts) valueProducts)
[IMO] `Function(値)`の値はコレクション型じゃないんですよ

2022-10-03 06:29 UTC, danielkaneko commented on ShoppingCart.Test/CommandDetectorTest.vb
> +        Assert.That(actual.Values(1).Name, [Is].EqualTo("鉛筆"))
レビューありがとうございます。
`.Value`を付けずに`actual(0).Name`のように入力すると、(0)の部分がKeyを示す値と判定されてしまうらしくInteger型からString方への型変換についてのエラーが出てしまい使えませんでした。

2022-10-03 06:29 UTC, danielkaneko commented on ShoppingCart/ProductsListMaker.vb
> +        Return productsList.ToDictionary(Of String, Products)(Function(keyProducts) keyProducts.Id, Function(valueProducts) valueProducts)
レビューありがとうございます。
値の名前が複数形になってしまっているという認識でよろしいでしょうか？

2022-10-03 06:32 UTC, Takatatsu9 commented on ShoppingCart.Test/CommandDetectorTest.vb
> +        Assert.That(actual.Values(1).Name, [Is].EqualTo("鉛筆"))
このテストってどの値がどこにあるかインデックスまで一致してないとダメ（＝並び順を検証したい）ですか？
それともキーさえあってればいいテスト（＝データがちゃんと取れているか検証したい）ですか？

2022-10-03 06:32 UTC, Takatatsu9 commented on ShoppingCart/ProductsListMaker.vb
> +        Return productsList.ToDictionary(Of String, Products)(Function(keyProducts) keyProducts.Id, Function(valueProducts) valueProducts)
その通りです

2022-10-03 06:40 UTC, danielkaneko commented on ShoppingCart.Test/CommandDetectorTest.vb
> +        Assert.That(actual.Values(1).Name, [Is].EqualTo("鉛筆"))
並び順ではなくデータがちゃんと取れているかを検証したいテストです。

2022-10-03 06:40 UTC, danielkaneko commented on ShoppingCart/ProductsListMaker.vb
> +        Return productsList.ToDictionary(Of String, Products)(Function(keyProducts) keyProducts.Id, Function(valueProducts) valueProducts)
ありがとうございます。
値の名前を修正いたします。

2022-10-03 23:53 UTC, konta3291 reviewed
Done

2022-10-04 00:03 UTC, nabemasamasa reviewed
Done

2022-10-04 00:03 UTC, nabemasamasa commented on ShoppingCart/ProductsListMaker.vb
>          Dim productsList As New List(Of Products) From {
[Q] そういえば、このメソッドのテストってあるんでしたっけ？

2022-10-04 00:13 UTC, danielkaneko commented on ShoppingCart/ProductsListMaker.vb
>          Dim productsList As New List(Of Products) From {
レビューありがとうございます。
テストはありませんので追加いたします。

2022-10-06 02:25 UTC, Takatatsu9 commented on ShoppingCart.Test/CommandDetectorTest.vb
> +        Assert.That(actual.Values(1).Name, [Is].EqualTo("鉛筆"))
書き忘れてましたけど
3日（月）の作業報告で、値を検証したいなら`actual.Values(index).Name`じゃなくて
`actual(key).Name`って書いて検証していいじゃんって話をしました。

2022-10-06 05:50 UTC, danielkaneko commented on ShoppingCart/ProductsListMaker.vb
>          Dim productsList As New List(Of Products) From {
修正いたしました。
コミットハッシュ： ccd7bfd

2022-10-06 05:50 UTC, danielkaneko commented on ShoppingCart/ProductsListMaker.vb
> +        Return productsList.ToDictionary(Of String, Products)(Function(keyProducts) keyProducts.Id, Function(valueProducts) valueProducts)
修正いたしました。
コミットハッシュ： 7e5b963

2022-10-06 06:08 UTC, danielkaneko commented on ShoppingCart.Test/CommandDetectorTest.vb
> +        Assert.That(actual.Values(1).Name, [Is].EqualTo("鉛筆"))
2f50154 のコミットにて検索や並び替えをする機能をList型で行うようにいたしましたので、指摘を頂いた箇所は`actual(1).Name`のような形に修正いたしました。

2022-10-06 06:41 UTC, konta3291 reviewed
Done

2022-10-06 06:41 UTC, konta3291 commented on ShoppingCart.Test/ProductsListMakerTest.vb
> +        Console.WriteLine(ToString(actual.Values))
[Q]Console.WriteLine(ToString(actual.Values))ってテストを行う上で何の役割をしているのですか？

2022-10-06 06:41 UTC, konta3291 commented on ShoppingCart/Products.vb
> +    Public Property Id As String
[Q]ReadOnlyはなぜ無くしたのですか？理由があれば教えていただきたいです。

2022-10-06 06:53 UTC, danielkaneko commented on ShoppingCart/Products.vb
> +    Public Property Id As String
レビューありがとうございます。
`ProductsListMakerTest`で行うテストで`DebugStringMaker`を使用するため消しました。

2022-10-06 06:53 UTC, danielkaneko commented on ShoppingCart.Test/ProductsListMakerTest.vb
> +        Console.WriteLine(ToString(actual.Values))
レビューありがとうございます。
テストを行う際に値を確認しようと思い追加したものを消し忘れていました。
削除いたします。

2022-10-06 06:55 UTC, konta3291 commented on ShoppingCart.Test/ProductsListMakerTest.vb
> +        Console.WriteLine(ToString(actual.Values))
ご回答ありがとうございます。
かしこまりました。

2022-10-06 06:57 UTC, danielkaneko commented on ShoppingCart.Test/ProductsListMakerTest.vb
> +        Console.WriteLine(ToString(actual.Values))
修正いたしました。
コミットハッシュ： a601e5b

2022-10-06 07:04 UTC, konta3291 commented on ShoppingCart/Products.vb
> +    Public Property Id As String
ご回答ありがとうございます。
わかりました、ありがとうございます。
私はDebugStringMakerを使ったことがなく、検索しても見つからなかったのでお聞きするのですが、
DebugStringMakerはどうやって使うのでしょうか。
お忙しいところ申し訳ないのですがお時間があるとき教えていただきたいです。

2022-10-06 07:04 UTC, konta3291 reviewed
Done

2022-10-06 07:05 UTC, Takatatsu9 reviewed
Done

2022-10-06 07:05 UTC, Takatatsu9 commented on ShoppingCart/Products.vb
> +    Public Property Id As String
ReadOnlyつけてると使えないんだっけ？
もし`Bind(vo.Id)`や`BindWithTitle(vo.Id, "Id")`がダメなら
`BindFuncWithTitle(Function() vo.Id, "Id")`を試してみて

2022-10-06 07:05 UTC, Takatatsu9 commented on ShoppingCart/Products.vb
> +    Public Sub New()
（実はコンストラクタはコメント書かなくてもよかったりする。引数あるなら書いてくれたほうが嬉しいけど）

2022-10-06 07:05 UTC, Takatatsu9 commented on ShoppingCart.Test/CommandDetectorTest.vb
> -        Dim actual As Dictionary(Of String, Products) = rlirtc.ReturnSearchNameList("--name 鉛筆", productsList)
> 商品リストを管理する場所以外をList型に修正

[Q] なんで？

2022-10-06 07:08 UTC, Takatatsu9 commented on ShoppingCart/Products.vb
> +    Public Property Id As String
@konta3291 
DebugStringMakerはダニエル三鷹チームが作って使ってるモノなのでいくら調べても絶対に出てきません。

2022-10-06 07:18 UTC, danielkaneko commented on ShoppingCart.Test/CommandDetectorTest.vb
> -        Dim actual As Dictionary(Of String, Products) = rlirtc.ReturnSearchNameList("--name 鉛筆", productsList)
3日の作業報告にて商品リストの管理を行う場所以外はList型のままでよいとの指摘を頂きましたので、Dictionary型に変更した`CommandDetector`のメソッドの引数や戻り値をList型に修正いたしました。

2022-10-06 07:18 UTC, danielkaneko commented on ShoppingCart/Products.vb
> +    Public Sub New()
レビューありがとうございます。

2022-10-06 07:19 UTC, danielkaneko commented on ShoppingCart/Products.vb
> +    Public Property Id As String
@Takatatsu9 
ありがとうございます。
`Bind(vo.Id)`の書き方だとReadOnlyを付けていると使えないのでご提示いただいた方法を試してみます。

2022-10-06 07:24 UTC, konta3291 commented on ShoppingCart/Products.vb
> +    Public Property Id As String
@Takatatsu9 
いくら探しても見つからなかった理由がわかりました。
ありがとうございます。

2022-10-06 07:36 UTC, nabemasamasa commented on ShoppingCart/Products.vb
> +    Public Property Id As String
あー……そっかラムダ式ならVoPropertyMakerでマーキングしないからReadOnly出力できたっけ…………忘れてた……。
是非Tryしてほしいです！

2022-10-06 07:44 UTC, Takatatsu9 commented on ShoppingCart.Test/CommandDetectorTest.vb
> -        Dim actual As Dictionary(Of String, Products) = rlirtc.ReturnSearchNameList("--name 鉛筆", productsList)
ん－、つまりこういうことですね。
コミットコメントに書くべきはWHAT（何をしたか）ではなくWHY（なぜその対応をする必要があるのか）を
書くべきだというのは、たぶん教えたような気がすると思うんですけど、どうだったっけ。

それは置いといて、コミットコメントの書き方の前提通りにコミットコメントを修正すると、その回答ならば
「List型のままでいいと言われたのでList型に修正」と書くことになりますけど、それでいいんでしょうか？

2022-10-06 08:43 UTC, nabemasamasa commented on ShoppingCart.Test/CommandDetectorTest.vb
> -        Dim actual As Dictionary(Of String, Products) = rlirtc.ReturnSearchNameList("--name 鉛筆", productsList)
(コミットコメントはWhyを書く、は気軽に発言してるから、教えてるはず……
何ならちょっと前にどこかのPRでも言ってそう。何なら、指摘に対して理解できてないとWhy書けないと思うんですけどどうしてそういう指摘があったのかWhy理解できてますか？って聞いた気もする)

2022-10-06 08:52 UTC, nabemasamasa reviewed
done

2022-10-06 08:52 UTC, nabemasamasa commented on ShoppingCart.Test/ProductsListMakerTest.vb
> +                            [Is].EqualTo("Id       Name           Inventory Price Inventory" & vbCrLf &
あぁ、二重Inventoryは確かにおかしい……無駄だ……(作業報告の時に言ってたのコレか…)
VisualStudioなら Shift + Alt + 矢印で矩形選択が使えるから、簡単に範囲削除できるはず

2022-10-06 09:18 UTC, danielkaneko commented on ShoppingCart.Test/CommandDetectorTest.vb
> -        Dim actual As Dictionary(Of String, Products) = rlirtc.ReturnSearchNameList("--name 鉛筆", productsList)
> コミットコメントに書くべきはWHAT（何をしたか）ではなくWHY（なぜその対応をする必要があるのか）を
書くべきだというのは、たぶん教えたような気がすると思うんですけど、どうだったっけ。

コミットコメントにつきましてWHYを書くというのはすでに教わっております。
WHATの書き方をしてしまい、申し訳ございません。

> それは置いといて、コミットコメントの書き方の前提通りにコミットコメントを修正すると、その回答ならば
「List型のままでいいと言われたのでList型に修正」と書くことになりますけど、それでいいんでしょうか？

申し訳ございません。回答が適切ではありませんでした。
`CommandDetector`にて検索や並び替えを行う際には、Keyを設定して同名の商品等を管理する必要がないためList型に修正いたしました。


コミットコメントをWHYの書き方に修正いたします。

2022-10-06 09:18 UTC, danielkaneko commented on ShoppingCart.Test/ProductsListMakerTest.vb
> +                            [Is].EqualTo("Id       Name           Inventory Price Inventory" & vbCrLf &
レビューありがとうございます。

2022-10-07 00:00 UTC, Takatatsu9 commented on ShoppingCart.Test/CommandDetectorTest.vb
> -        Dim actual As Dictionary(Of String, Products) = rlirtc.ReturnSearchNameList("--name 鉛筆", productsList)
「WHYの書き方に修正」？「WHYを書くように修正」じゃなくて？
（本当に理解してんのかな、オウム返ししてるだけじゃねーのかな）

2022-10-07 00:41 UTC, danielkaneko commented on ShoppingCart.Test/CommandDetectorTest.vb
> -        Dim actual As Dictionary(Of String, Products) = rlirtc.ReturnSearchNameList("--name 鉛筆", productsList)
申し訳ございません。
WHYという言葉を（なぜその対応をする必要があるのか）そのままの意味ではなく
（なぜその対応をする必要があるのかを書くという形式）という意味でとらえておりました。

2022-10-07 01:37 UTC, danielkaneko commented on ShoppingCart.Test/ProductsListMakerTest.vb
> +                            [Is].EqualTo("Id       Name           Inventory Price Inventory" & vbCrLf &
修正いたしました。
コミットハッシュ： 68f3347

2022-10-07 01:38 UTC, danielkaneko commented on ShoppingCart.Test/CommandDetectorTest.vb
> -        Dim actual As Dictionary(Of String, Products) = rlirtc.ReturnSearchNameList("--name 鉛筆", productsList)
修正いたしました。
コミットハッシュ： ff619f6

2022-10-07 01:38 UTC, danielkaneko commented on ShoppingCart/Products.vb
> +    Public Property Id As String
修正いたしました。
コミットハッシュ： c4c43de

2022-10-07 01:38 UTC, danielkaneko commented
コミットコメントを修正したため強制プッシュを行いました。

2022-10-07 01:47 UTC, nabemasamasa commented
強制プッシュする事で、既にレビュー済みの内容をレビューすることになってませんか？

2022-10-07 01:57 UTC, danielkaneko commented
申し訳ございません。
レビューをお願いする立場でありながらレビュアーへの配慮が足りておりませんでした。
レビューしてほしいコミットをコメントに追加いたしました。

2022-10-07 02:09 UTC, nabemasamasa commented
[Q] ちなみに、コミットコメントのみの修正ってありますか？コードもレビューしなさないといけませんか？中身が変わってなくても？

2022-10-07 02:31 UTC, danielkaneko commented
ff619f6 がコミットコメントのみの修正になります。
修正の中身が変わっていないのでコードのレビューは必要ありません。
修正前のコミットコメントがWHATだったものをWHYに直したものですので、WHYになっているかを確認していただきたいです。

2022-10-07 05:25 UTC, Takatatsu9 reviewed
Done

2022-10-07 05:25 UTC, Takatatsu9 commented on ShoppingCart.Test/CommandDetectorTest.vb
> +        Dim actual As List(Of Products) = rlirtc.FilterListByName("--name 鉛筆", productsList.Values.ToList)
（この100人中100人が意味わからない`rlirtc`は放置なんだな）

2022-10-07 05:25 UTC, Takatatsu9 commented on ShoppingCart.Test/ProductsListMakerTest.vb
> +                                         "'MPN-1'  '消しゴム'     'モノけし'                 120        30" & vbCrLf &
コーディングとは全く関係無いんですけどモノけしってどんなモノなんですか？

2022-10-07 05:35 UTC, danielkaneko commented on ShoppingCart.Test/CommandDetectorTest.vb
> +        Dim actual As List(Of Products) = rlirtc.FilterListByName("--name 鉛筆", productsList.Values.ToList)
レビューありがとうございます。
申し訳ございません。修正漏れがありました。
意味が分かる変数名に修正いたします。

2022-10-07 05:36 UTC, danielkaneko commented on ShoppingCart.Test/ProductsListMakerTest.vb
> +                                         "'MPN-1'  '消しゴム'     'モノけし'                 120        30" & vbCrLf &
レビューありがとうございます。
実際に存在している商品ではないのですが
MONO消しゴムのオマージュ商品のようなものだと認識していただければと思います。

2022-10-07 05:37 UTC, Takatatsu9 commented on ShoppingCart.Test/ProductsListMakerTest.vb
> +                                         "'MPN-1'  '消しゴム'     'モノけし'                 120        30" & vbCrLf &
なるほど、ブランドですか。キン消しみたいなものかと思いました。

2022-10-07 05:39 UTC, Takatatsu9 commented on ShoppingCart.Test/CommandDetectorTest.vb
> +        Dim actual As List(Of Products) = rlirtc.FilterListByName("--name 鉛筆", productsList.Values.ToList)
修正漏れっていうのは、修正すべきなのを見逃していたのを言うのであって、
直す気がなくて意図的に放置してたのは修正漏れとは言いません。

2022-10-07 05:57 UTC, danielkaneko commented on ShoppingCart.Test/CommandDetectorTest.vb
> +        Dim actual As List(Of Products) = rlirtc.FilterListByName("--name 鉛筆", productsList.Values.ToList)
意図的に放置していたわけではないので修正漏れだと思います。
以前同じような指摘を頂いた際にShoppingCart側の修正のみで修正を終えたと思ってしまい、今回指摘を頂くまでShoppingCart.Testの修正箇所に気づかず忘れておりました。
今回指摘を頂いた箇所以外にも`MeaningfulInputCheckerTest`にも同様の変数がありますので修正いたします。
申し訳ございませんでした。

2022-10-07 06:24 UTC, danielkaneko commented on ShoppingCart.Test/CommandDetectorTest.vb
> +        Dim actual As List(Of Products) = rlirtc.FilterListByName("--name 鉛筆", productsList.Values.ToList)
修正いたしました。
コミットハッシュ： 1b8f7c9

2022-10-09 22:56 UTC, nabemasamasa reviewed
Done

2022-10-10 02:59 UTC, konta3291 reviewed
Done

2022-10-10 05:16 UTC, Takatatsu9 reviewed
Done

2022-10-10 05:17 UTC, Takatatsu9 commented
@nabemasamasa 上の指摘がまだUnresolvedですけどまだ修正されてません？

2022-10-10 05:27 UTC, nabemasamasa commented
失礼しました、「`コミットハッシュ`  修正しました」コメントがなくてResolveすべきか、判断に困ってました。
たぶん、解決済みだとは思いますが、確認します。

2022-10-10 05:28 UTC, nabemasamasa commented on ShoppingCart/GoodsListMaker.vb
> +﻿Public Class GoodsListMaker
333ff0c8eb82d4b4b86139089042b109865e2da0 で修正済みを確認

2022-10-10 05:28 UTC, nabemasamasa commented on ShoppingCart/ListShower.vb
> +﻿Public Class ListShower
333ff0c8eb82d4b4b86139089042b109865e2da0 で修正済みを確認。

2022-10-10 05:28 UTC, nabemasamasa commented on ShoppingCart/GoodsListMaker.vb
> +        Public goodsName As String
e1afc940bdf2dbb99538c09cd7e7dc5767b51761 で修正を確認。

2022-10-10 05:29 UTC, nabemasamasa commented on ShoppingCart/GoodsListMaker.vb
> +    Public Function RegisterGoodsList() As List(Of GoodsProperty)
cc1675d514c4fff04c2ac9066845d862b210c87a で修正を確認

2022-10-10 05:29 UTC, nabemasamasa commented on ShoppingCart/ListShower.vb
> +        For Each list In goodsList
2882bbaf282a62eb610f9f9d9b6f3c20cf1d2020 で修正を確認

2022-10-10 05:30 UTC, nabemasamasa commented on ShoppingCart/ListShower.vb
> +                          "価格：" & list.goodsPrice & "円" & vbCrLf & "在庫数：" & list.goodsInventory)
f2ec7cdc308f797c4ccb2daa817bae43bbe9c2a6 で修正を確認

2022-10-10 05:31 UTC, nabemasamasa commented on ShoppingCart/MeaningfulInputChecker.vb
> +    Public Function CheckInputCommand(inputCommand As String) As Boolean
b5ea1dff18e8ad87e436f50a154d81f722616ebb で修正を確認

2022-10-10 05:31 UTC, nabemasamasa commented on ShoppingCart/StringExtraction.vb
> +        Return inputContent.Split(CChar(delimiter))
761589f2ae2b6562a375d6a35f16561c59708d51 6d079b0ae19a87cd1821a9ec887133fd63c41a31 で修正を確認

2022-10-10 05:32 UTC, nabemasamasa commented on ShoppingCart/Main.vb
> +            ls.ShowList(goodsList.FindAll(Function(name) name.goodsName.Contains(inputCommand.Substring(7))))
4a589793e1ed30af7f2a678255a4fa42369cc452 で修正を確認

2022-10-10 05:33 UTC, nabemasamasa commented on ShoppingCart/MeaningfulInputChecker.vb
> +        IsExit = False
307e07ae869220719852f6415195ace67df31a57 で修正を確認

2022-10-10 05:34 UTC, nabemasamasa commented on ShoppingCart/GoodsListMaker.vb
> +    Public Class GoodsProperty
ff6d6f83ef940de7b5135b7743829f91a1d3acdd 090ff8c2e3c1c5e387b2ebaf513cd6b7c46965f1 で修正を確認

2022-10-10 05:38 UTC, nabemasamasa commented
修正が確認できた指摘や、独り言など一通りResolveしてきました。
これでUnresolvedのままの修正しないといけないような指摘はないはず……。

2022-10-11 06:43 UTC, danielkaneko commented
@nabemasamasa 
@Takatatsu9 
@konta3291 
コミット整理を行い強制プッシュを行いました。
変更は加えていないためレビューはしていただかなくて大丈夫です。

2022-10-11 07:42 UTC, Takatatsu9 reviewed
Done

2022-10-12 05:25 UTC, konta3291 reviewed
Done

2022-10-17 07:39 UTC, nabemasamasa reviewed
Abort

2022-10-17 07:45 UTC, merged